# Generated by Django 3.2.9 on 2021-11-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductProductimage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'product_productimage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductProductvariant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('variant_title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product_productvariant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductProductvariantprice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('stock', models.FloatField()),
            ],
            options={
                'db_table': 'product_productvariantprice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'product_variant',
                'managed': False,
            },
        ),
    ]
